import = ["~/.config/alacritty/themes/dracula.toml"]

[font]
size = 18.0

[font.normal]
family = "Hack Nerd Font Mono"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.offset]
x = 0
y = 2

[window]
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
