tap "homebrew/bundle"
tap "homebrew/core"

brew "coreutils"
brew "asdf"
brew "autojump"
brew "awscli"
brew "bat"
brew "curl"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gitui"
brew "glow"
brew "gnupg"
brew "lsd"
brew "neovim"
brew "pinentry"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
brew "zsh"

if OS.linux?
  brew "pinentry"
end

if OS.mac?
  brew "reattach-to-user-namespace"
  brew "pinentry-mac"

  tap "homebrew/cask"
  cask "1password"
  cask "1password-cli"
  cask "alacritty"
  cask "aws-vpn-client"
  cask "discord"
  cask "docker"
  cask "figma"
  cask "franz"
  cask "google-chrome"
  cask "jetbrains-toolbox"
  cask "keeweb"
  cask "keybase"
  cask "microsoft-auto-update"
  cask "microsoft-office"
  cask "mongodb-compass"
  cask "notion"
  cask "sizzy"
  cask "slack"
  cask "visual-studio-code"
  cask "zoom"

  tap "homebrew/cask-fonts"
  cask "font-hack-nerd-font"
end
