brew "aws-vault"
brew "awscli"
brew "awscli-local"
brew "bat"
brew "capnp"
brew "cmake"
brew "curl"
brew "dust"
brew "fd"
brew "fontconfig"
brew "gh"
brew "git"
brew "gitui"
brew "git-delta"
brew "glow"
brew "gnupg"
brew "gnuplot"
brew "gource"
brew "hyperfine"
brew "localstack"
brew "lsd"
brew "mise"
brew "neovim"
brew "ollama"
brew "pnpm"
brew "ripgrep"
brew "sccache"
brew "television"
brew "watchman"
brew "wget"
brew "yarn"
brew "zellij"
brew "zoxide"

brew "sst/tap/opencode"

if OS.linux?
  brew "pinentry"
  brew "zsh"
end

if OS.mac?
  brew "gnu-tar"
  brew "reattach-to-user-namespace"
  brew "pinentry-mac"
  brew "pngpaste"

  tap  "jorgelbg/tap"
  brew "pinentry-touchid"

  cask "1password"
  cask "1password-cli"
  cask "alacritty"
  cask "android-platform-tools"
  cask "chatgpt"
  cask "discord"
  cask "figma"
  cask "firefox@developer-edition"
  cask "gcloud-cli"
  cask "google-chrome"
  cask "google-drive"
  cask "keeweb"
  cask "keybase"
  cask "keycastr"
  cask "notion"
  cask "orbstack"
  cask "slack"
  cask "typora"
  cask "visual-studio-code"
  cask "zed"

  # May conflict with MDM
  # cask "zoom"

  cask "font-hack-nerd-font"
  cask "font-noto-sans-cjk"
  cask "font-noto-sans-cjk-kr"
  cask "font-sf-pro"
  cask "font-pretendard"
end
